name: DevOps K8s CI
 
on:

  push:

    branches: [ main, develop ]

  pull_request:

    branches: [ main, develop ]
 
jobs:

  k8s-test:

    runs-on: ubuntu-latest
 
    steps:

    - name: Checkout local repository

      uses: actions/checkout@v3
 
    - name: Start Minikube Cluster

      uses: medyagh/setup-minikube@master

      with:

        minikube-version: 'latest'

        driver: 'docker'
 
    # Étape corrigée avec le bon chemin vers le sous-dossier k8s

    - name: Apply DevOps Infrastructure

      run: |

        kubectl apply -f k8s/infrastructure.yaml
 
    - name: Check K8s Resources Status

      run: |

        kubectl get deployments

        kubectl get pods

        kubectl get services
 